#配置端口号
server:
  port: 8001

spring:
  servlet:
    multipart:
      enabled: true
      location: uploads
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: engteach.entity