#配置端口号
server:
  port: 8002

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/eng_teach?serverTimezone=GMT%2B8
    username: root
    password: Jason20040903
  mail:
    host: smtp.qq.com
    port: 465
    username: 1363180320@qq.com
    password: vekcmqflhtlniahe
    properties:
      mail:
        smtp:
          auth: true
          # 设置SSL为true
          ssl:
            enable: true
          # 设置TLS为false
          starttls:
            enable: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: engteach.user.entity